dist:
  - bionic

os:
  - linux

compiler:
  - gcc

addons:
  apt:
    packages:
      - cmake
      - libxerces-c-dev

script:
  - mkdir build && cd build && cmake .. -DCMAKE_BUILD_TYPE=Release
  - cmake --build . --config Release
  - ctest -C Release --output-on-failure
