language: cpp
compiler:
  - gcc
script:
  - cmake --version
  - mkdir -p build && cd build && cmake .. && make
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y libxerces-c-dev
  - wget http://www.cmake.org/files/v3.0/cmake-3.0.1-Linux-i386.tar.gz
  - tar -xzf cmake-3.0.1-Linux-i386.tar.gz
  - sudo cp -fR cmake-3.0.1-Linux-i386/* /usr
  - rm -rf cmake-3.0.1-Linux-i386
  - rm cmake-3.0.1-Linux-i386.tar.gz
