language: cpp
compiler:
  - gcc
script:
  - ./cmake/bin/cmake --version
  - mkdir -p build && cd build && ../cmake/bin/cmake .. && make
before_install:
  - wget -qO- http://www.cmake.org/files/v3.1/cmake-3.1.0-Linux-x86_64.tar.gz | tar xvz
  - mv cmake-3.1.0-Linux-x86_64 cmake

addons:
  apt:
    packages:
      - libxerces-c-dev

sudo: false
