install:
  - cinst biicode
  - cmd: set PATH=%PATH:CMake 2.8\bin=%;C:\ProgramData\chocolatey\lib\cmake.3.0.2\content\cmake-3.0.2-win32-x86\bin
  - cmd: set PATH=%PATH%;C:\Program Files (x86)\BiiCode\bii;
  - cmd: bii --version
  - cmd: cmake --version
