version: "1.0.2.{build}"

image:
  - Visual Studio 2017

environment:
  CMAKE_GENERATOR: "Visual Studio 15 2017 Win64"
  CMAKE_BUILD_TYPE: "Release"

build_script:
  - cmd: echo "Generator='%CMAKE_GENERATOR%', CMAKE_BUILD_TYPE='%CMAKE_BUILD_TYPE%'"
  - cmd: cmake --version
  - cmd: mkdir build
  - cmd: cd build
  - cmd: cmake -G "%CMAKE_GENERATOR%" ..
  - cmd: cmake --build . --config %CMAKE_BUILD_TYPE%
  - cmd: ctest -C %CMAKE_BUILD_TYPE% --output-on-failure
