version: "1.0.2.{build}"

image:
  - Visual Studio 2017

environment:
  CMAKE_GENERATOR: "Visual Studio 15 2017 Win64"
  CMAKE_BUILD_TYPE: "Release"

build_script:
  - cmd: echo "Generator='%CMAKE_GENERATOR%', CMAKE_BUILD_TYPE='%CMAKE_BUILD_TYPE%'"
  - cmd: echo "Platform='%Platform%'"
  - cmd: cmake --version
  - cmd: mkdir build
  - cmd: cd build
  - cmd: cmake -G "%CMAKE_GENERATOR%" ..
  - cmd: cmake --build . --config %CMAKE_BUILD_TYPE%

test_script:
  - cmd: cd bin
  - cmd: ksons_xiot_tests_IOTest.exe
  - cmd: ksons_xiot_tests_shapeCounter.exe iotest.x3d
